In [1]:
import cv2

In [5]:
im_g = cv2.imread("occhio.jpg",0)
im_g

array([[145, 143, 141, ..., 104, 105, 106],
       [144, 143, 141, ..., 104, 105, 105],
       [144, 143, 140, ..., 104, 104, 105],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [14]:
im_g = cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [8]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [9]:
a = [1,2,3]

In [10]:
a(0:1)

SyntaxError: invalid syntax (<ipython-input-10-705c2e77f4b9>, line 1)

In [12]:
a[0:2]

[1, 2]

In [16]:
im_g[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [17]:
im_g.shape

(3, 5)

In [20]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [21]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [22]:
ims = numpy.hstack((im_g, im_g))

NameError: name 'numpy' is not defined

In [23]:
import numpy

In [34]:
ims = numpy.vstack((im_g, im_g, im_g))

In [35]:
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [44]:
lst = numpy.vsplit(ims, 3)

In [45]:
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [46]:
lst[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)